phrase = "Don't panic!"
plist = list(phrase)
print(phrase)
print(plist)
new_phrase = ''.join(plist)
print(plist)
print(new_phrase)
plist.pop(0)
plist.pop(2)
plist.pop(2)
plist.insert(3,'t')
plist.pop(4)
plist.pop()
plist.pop()
plist.pop()
plist.pop()
plist.extend(['p','e'])
print(plist)
new_phrase1 = ''.join(plist)
print(new_phrase1)
